<?php

function hello_menu() {
 
  $items = array(
      'hello_world' => array(
        'title' => 'Hello world',
        'page callback' => '_page_hello_world',
        'access callback' => TRUE,
      ),
    );

  $items['admin/config/content/hello'] = array(
    'title' => 'Hello config',
    'description' => 'Configuration du module hello',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('hello_config_form'),
    'access arguments' => array('access hello content')
  ); 

  return $items;
}

function hello_theme() {
  return array(
    'hello_text' => array(
      'template' => 'hello-text',
      'variables' => array('text' => NULL)
    ),
  );
}
 
function _page_hello_world() {
//  return array(    '#markup' => '<p>Hello world</p>' );
  return theme('hello_text', array('text' => 'YBA'));
}

function hello_block_info() {
  $blocks['hello'] = array(
    'info' => t('Hello world'),
  );
  return $blocks;
}
 
function hello_block_view($delta = '') {
  global $user;
  switch ($delta) {
    case 'hello':
      $block['subject'] = t('Hello world');
//      $block['content'] = 'Hello '.$user->name;
      $block['content'] = 'Hello '.$user->name.' ('.variable_get('hello_text', 'anonymous').')<br>';
      break;
  }
  return $block;
}

function hello_permission() {
  return array(
    'access hello content' => array(
      'title' => t('Access hello content')
    )
  );
}

function hello_config_form() {
  $form['hello_config'] = array(
    '#type' => 'textfield',
    '#title' => t('Who are you ?'),
    '#size' => 10,
    '#default_value' => variable_get('hello_text', 'anonymous'),
  );
 
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
 
  return $form;
}
 
function hello_config_form_submit($form, $form_state) {
  variable_set('hello_text', $form_state['values']['hello_config']);
}
